// ── Config per type ───────────────────────────────────────────────────────
export const TYPE_CONFIG = {
  customers: {
    label:          'Customers',
    color:          'blue',
    btnColor:       'bg-blue-600 hover:bg-blue-700',
    borderHover:    'hover:border-blue-400',
    infoBg:         'bg-blue-50 text-blue-800',
    icon:           '🧑‍💼',
    requiredColumns: ['name', 'email', 'phone', 'address_town', 'address_postcode'],
    previewColumns:  [
      { key: 'name',             label: 'Company Name' },
      { key: 'email',            label: 'Email' },
      { key: 'phone',            label: 'Phone' },
      { key: 'address_town',     label: 'Town' },
      { key: 'address_postcode', label: 'Postcode' },
    ],
  },
  suppliers: {
    label:          'Suppliers',
    color:          'purple',
    btnColor:       'bg-purple-600 hover:bg-purple-700',
    borderHover:    'hover:border-purple-400',
    infoBg:         'bg-purple-50 text-purple-800',
    icon:           '🏭',
    requiredColumns: ['name', 'email', 'phone', 'address_town', 'address_postcode'],
    previewColumns:  [
      { key: 'name',             label: 'Company Name' },
      { key: 'email',            label: 'Email' },
      { key: 'phone',            label: 'Phone' },
      { key: 'address_town',     label: 'Town' },
      { key: 'address_postcode', label: 'Postcode' },
    ],
  },
  stockItems: {
    label:          'Stock Items',
    color:          'orange',
    btnColor:       'bg-orange-600 hover:bg-orange-700',
    borderHover:    'hover:border-orange-400',
    infoBg:         'bg-orange-50 text-orange-800',
    icon:           '📦',
    requiredColumns: ['name', 'sku', 'type', 'sale_price', 'cost_price'],
    previewColumns:  [
      { key: 'name',        label: 'Name' },
      { key: 'sku',         label: 'SKU' },
      { key: 'type',        label: 'Type' },
      { key: 'sale_price',  label: 'Sale Price' },
      { key: 'cost_price',  label: 'Cost Price' },
    ],
  },
  journals: {
    label:          'Journals',
    color:          'blue',
    btnColor:       'bg-blue-600 hover:bg-blue-700',
    borderHover:    'hover:border-blue-400',
    infoBg:         'bg-blue-50 text-blue-800',
    icon:           '📓',
    requiredColumns: ['journal_ref', 'accounting_date', 'description', 'lines'],
    previewColumns:  [
      { key: 'journal_ref',     label: 'Journal Ref' },
      { key: 'accounting_date', label: 'Date' },
      { key: 'description',     label: 'Description' },
      { key: 'lines',           label: 'Lines' },
    ],
  },
};